### ISSUE TITLE
Joining Eclipse Nebula ?

### ISSUE THREAD

**Issue by lcaron** [prasser/swttiles#4]
Hi,

Your widget is very interesting, have you ever thought about including this widget to Eclipse Nebula (https://www.eclipse.org/nebula) ?

Feel free to contact me if you're interested.

**Comment by prasser** [comment]
Hi Laurent,

that would be great. However, I don't have a lot of ressources that I could invest into this at the moment. How would we proceed from here?

Best
Fabian

**Comment by lcaron** [comment]
Hi Fabian,

Thank you for your feedback.

Well, I can help if you run out of time (migration to the Nebula Structure). 
The only thing you have to do is signing the Eclipse Contributor Agreement (https://www.eclipse.org/legal/ECA.php). 
Maybe have you already signed it ?

Feel free to ask ;)

Laurent

**Comment by prasser** [comment]
I just signed the ECA! Best, Fabian

**Comment by lcaron** [comment]
Perfect !

Here is my proposal : I do the migration and send you the source code, so you'll just have to create a pull request and push it (so you'll be the author of the commit).

What do you think ?

Laurent

**Comment by prasser** [comment]
If that's your preferred way, I'm fine with it!

**Comment by lcaron** [comment]
Hi Fabian,

First of all let me wish you an happy new year.

I would like to inform you that Tiles is now part of the Nebula Project : https://github.com/eclipse/nebula/tree/master/widgets/tiles

The documentation has also been added to the Eclipse Wiki : https://wiki.eclipse.org/Nebula_Tiles

Thank you for your trust and welcome into the Nebula family !
